### ISSUE TITLE
Broke high brightness mode on yaap

### ISSUE THREAD

**Issue by WewillChen** [mvaisakh/oneplus7#1]
High brightness mode toggle keeps on.

**Comment by mvaisakh** [comment]
Hi, thanks for the feedback.
Can you attach a log?

Open HBM settings, turn it on and then turn it off and send a log using
`adb shell dmesg > dmesg.log`
and
`adb logcat -b all > logcat.log`

and send the dmesg.log and logcat.log files as an attachment here.

**Comment by WewillChen** [comment]
Done.
[dmesg.log](https://github.com/mvaisakh/oneplus7/files/6922007/dmesg.log)
[logcat.log](https://github.com/mvaisakh/oneplus7/files/6922008/logcat.log)

**Comment by WewillChen** [comment]
> Hi, thanks for the feedback.
> Can you attach a log?
> 
> Open HBM settings, turn it on and then turn it off and send a log using
> `adb shell dmesg > dmesg.log`
> and
> `adb logcat -b all > logcat.log`
> 
> and send the dmesg.log and logcat.log files as an attachment here.

Need anything else?

**Comment by mvaisakh** [comment]
> Need anything else?

Logs have what I needed, I'll share a build here. Can you try flashing it?

**Comment by WewillChen** [comment]
> > Need anything else?
> 
> Logs have what I needed, I'll share a build here. Can you try flashing it?

Ofc

**Comment by mvaisakh** [comment]
> Ofc

Try this build, and let me know if it fixes your issue. If it doesn't, fetch another log.
[EvaKernel-Experimental-oneplus7series-20210803-1627930792.zip](https://github.com/mvaisakh/oneplus7/files/6930751/EvaKernel-Experimental-oneplus7series-20210803-1627930792.zip)

**Comment by WewillChen** [comment]
> > Ofc
> 
> Try this build, and let me know if it fixes your issue. If it doesn't, fetch another log.
> [EvaKernel-Experimental-oneplus7series-20210803-1627930792.zip](https://github.com/mvaisakh/oneplus7/files/6930751/EvaKernel-Experimental-oneplus7series-20210803-1627930792.zip)

Same issue.
[dmesg.log](https://github.com/mvaisakh/oneplus7/files/6930800/dmesg.log)


> > Ofc
> 
> Try this build, and let me know if it fixes your issue. If it doesn't, fetch another log.
> [EvaKernel-Experimental-oneplus7series-20210803-1627930792.zip](https://github.com/mvaisakh/oneplus7/files/6930751/EvaKernel-Experimental-oneplus7series-20210803-1627930792.zip)

Same issue.
[dmesg.log](https://github.com/mvaisakh/oneplus7/files/6930803/dmesg.log)
[logcat.log](https://github.com/mvaisakh/oneplus7/files/6930802/logcat.log)

**Comment by mvaisakh** [comment]
> > > Ofc
> > 
> > 
> > Try this build, and let me know if it fixes your issue. If it doesn't, fetch another log.
> > [EvaKernel-Experimental-oneplus7series-20210803-1627930792.zip](https://github.com/mvaisakh/oneplus7/files/6930751/EvaKernel-Experimental-oneplus7series-20210803-1627930792.zip)
> 
> Same issue.
> [dmesg.log](https://github.com/mvaisakh/oneplus7/files/6930800/dmesg.log)
> 
> > > Ofc
> > 
> > 
> > Try this build, and let me know if it fixes your issue. If it doesn't, fetch another log.
> > [EvaKernel-Experimental-oneplus7series-20210803-1627930792.zip](https://github.com/mvaisakh/oneplus7/files/6930751/EvaKernel-Experimental-oneplus7series-20210803-1627930792.zip)
> 
> Same issue.
> [dmesg.log](https://github.com/mvaisakh/oneplus7/files/6930803/dmesg.log)
> [logcat.log](https://github.com/mvaisakh/oneplus7/files/6930802/logcat.log)

Thanks, I'll investigate more and get back to you.
