### ISSUE TITLE
System Vibration slider broken or not visible on custom roms supporting it

### ISSUE THREAD

**Issue by fazilsheik96** [mvaisakh/oneplus7#2]
Probably due to the absence of vib configs.

**Comment by techyminati** [comment]
Care sharing logcats? Refer [here ](https://github.com/mvaisakh/oneplus7/issues/1#issuecomment-891045197) on how to take logcat :)

**Comment by mvaisakh** [comment]
Issue has been fixed with 209a1de092085f3b80def007a312e53e161bd2d9.
Will release soon
