### ISSUE TITLE
Boot loop on OOS11.0.2.1

### ISSUE THREAD

**Issue by gb0k** [mvaisakh/oneplus7#3]
Flash this kernel under TWRP, with magisk v23.
Got boot loop in the bootloader warning screen.
Phone is OnePlus 7 Pro.

**Comment by mvaisakh** [comment]
> Flash this kernel under TWRP, with magisk v23.
> Got boot loop in the bootloader warning screen.
> Phone is OnePlus 7 Pro.

That's strange, it works fine on OnePlus 7 non-pro.
Send me log files from `/sys/fs/pstore/`, after you face the bootloop.
You can access that from recovery.

**Comment by gb0k** [comment]
> > Flash this kernel under TWRP, with magisk v23.
> > Got boot loop in the bootloader warning screen.
> > Phone is OnePlus 7 Pro.
> 
> That's strange, it works fine on OnePlus 7 non-pro.
> Send me log files from `/sys/fs/pstore/`, after you face the bootloop.
> You can access that from recovery.

Ok, got that log file.
[console-ramoops-0.txt](https://github.com/mvaisakh/oneplus7/files/6930677/console-ramoops-0.txt)

**Comment by mvaisakh** [comment]
> > > Flash this kernel under TWRP, with magisk v23.
> > > Got boot loop in the bootloader warning screen.
> > > Phone is OnePlus 7 Pro.
> > 
> > 
> > That's strange, it works fine on OnePlus 7 non-pro.
> > Send me log files from `/sys/fs/pstore/`, after you face the bootloop.
> > You can access that from recovery.
> 
> Ok, got that log file.
> [console-ramoops-0.txt](https://github.com/mvaisakh/oneplus7/files/6930677/console-ramoops-0.txt)

Thanks, looks like there is a dm verity corruption happening, which is nothing to worry about. Can you try flashing vbmeta.img by extracting any payload.
Use this command
`fastboot flash --disable-verity --disable-verification vbmeta vbmeta.img`

**Comment by gb0k** [comment]
> > > > Flash this kernel under TWRP, with magisk v23.
> > > > Got boot loop in the bootloader warning screen.
> > > > Phone is OnePlus 7 Pro.
> > > 
> > > 
> > > That's strange, it works fine on OnePlus 7 non-pro.
> > > Send me log files from `/sys/fs/pstore/`, after you face the bootloop.
> > > You can access that from recovery.
> > 
> > 
> > Ok, got that log file.
> > [console-ramoops-0.txt](https://github.com/mvaisakh/oneplus7/files/6930677/console-ramoops-0.txt)
> 
> Thanks, looks like there is a dm verity corruption happening, which is nothing to worry about. Can you try flashing vbmeta.img by extracting any payload.
> Use this command
> `fastboot flash --disable-verity --disable-verification vbmeta vbmeta.img`

Will this command let me lose my data?
Because I'm encryption with f2fs on /data

**Comment by mvaisakh** [comment]
> Will this command let me lose my data?
> Because I'm encryption with f2fs on /data

No it won't

**Comment by gb0k** [comment]
> > Will this command let me lose my data?
> > Because I'm encryption with f2fs on /data
> 
> No it won't

After ran that fastboot command to disable verity and verification, my phone still boot looping.
Log attached.
[console-ramoops-v2.txt](https://github.com/mvaisakh/oneplus7/files/6931527/console-ramoops-v2.txt)

**Comment by mvaisakh** [comment]
> After ran that fastboot command to disable verity and verification, my phone still boot looping.
> Log attached.
> [console-ramoops-v2.txt](https://github.com/mvaisakh/oneplus7/files/6931527/console-ramoops-v2.txt)

Alright, I shall look into it and get back to you.

**Comment by mvaisakh** [comment]
Hi, can you try this build and let me know if it boots for you on OOS?
[EvaKernel-Experimental-OxygenOS-oneplus7series-20210820-1629.zip](https://github.com/mvaisakh/oneplus7/files/7026557/EvaKernel-Experimental-OxygenOS-oneplus7series-20210820-1629.zip)

**Comment by ggshuini** [comment]
+1
OnePlus 7 non-pro

**Comment by mvaisakh** [comment]
> +1
> OnePlus 7 non-pro

Can you try this build and report?

> [EvaKernel-Experimental-OxygenOS-oneplus7series-20210820-1629.zip](https://github.com/mvaisakh/oneplus7/files/7026557/EvaKernel-Experimental-OxygenOS-oneplus7series-20210820-1629.zip)

**Comment by gb0k** [comment]
> Hi, can you try this build and let me know if it boots for you on OOS?
> [EvaKernel-Experimental-OxygenOS-oneplus7series-20210820-1629.zip](https://github.com/mvaisakh/oneplus7/files/7026557/EvaKernel-Experimental-OxygenOS-oneplus7series-20210820-1629.zip)

Doesn't work, after i flashed it, my phone booted into TWRP.

**Comment by mvaisakh** [comment]
> > Hi, can you try this build and let me know if it boots for you on OOS?
> > [EvaKernel-Experimental-OxygenOS-oneplus7series-20210820-1629.zip](https://github.com/mvaisakh/oneplus7/files/7026557/EvaKernel-Experimental-OxygenOS-oneplus7series-20210820-1629.zip)
> 
> Doesn't work, after i flashed it, my phone booted into TWRP.

That's strange, my ramdisk doesn't have twrp

Grab a log files from /sys/fs/pstore/

**Comment by gb0k** [comment]
> > > Hi, can you try this build and let me know if it boots for you on OOS?
> > > [EvaKernel-Experimental-OxygenOS-oneplus7series-20210820-1629.zip](https://github.com/mvaisakh/oneplus7/files/7026557/EvaKernel-Experimental-OxygenOS-oneplus7series-20210820-1629.zip)
> > 
> > 
> > Doesn't work, after i flashed it, my phone booted into TWRP.
> 
> That's strange, my ramdisk doesn't have twrp
> 
> Grab a log files from /sys/fs/pstore/

Don't have any files under /sys/fs/pstore/
