### ISSUE TITLE
Bootloop on My OnePlus 7T Pro

### ISSUE THREAD

**Issue by doriandrey** [mvaisakh/oneplus7#4]
Bootloop on My OnePlus 7T Pro Oxygen OS 11.0.2.1

**Comment by mvaisakh** [comment]
Hi, I have had reports of OxygenOS variant of my kernel not booting at all on most devices. This is being looked at. I shall fix it as soon as possible. Thank you for your feedback, it is highly appreciated!

**Comment by doriandrey** [comment]
Thanks
